### ISSUE TITLE
Error - Undefined Array Key - Sage Starter Theme

### ISSUE THREAD

**Issue by jellymel0n** [short-pixel-optimizer/shortpixel-image-optimiser#107]
Noticed this issue while using the Sage starter theme with Short Pixel. When activating the plugin there is an error for the delete_option within the onActivate() function in /class/wp-shortpixel-settings.php. The call to `self::$_optionsMap['removeSettingsOnDeletePlugin']['key']` returns an error and there is not proper checking in place, so this defaults to an error for undefined array key. 

Adding a check ( `if(isset(self::$_optionsMap['removeSettingsOnDeletePlugin']['key']))` ) fixed this issue locally.

**Comment by pdobrescu** [comment]
hello @jellymel0n and thanks for reporting this!

We'll surely include a fix in the next release!

All the best

**Comment by pdobrescu** [comment]
this was fixed in https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/commit/f9f1261041886aefdf3b600db1ef2d18cf30941e and released in version 5.1.0.

Thanks again for reporting it @jellymel0n

**Comment by jellymel0n** [comment]
@pdobrescu Thats awesome, thanks for letting me know!
