### ISSUE TITLE
Broken svg images

### ISSUE THREAD

**Issue by matt08** [short-pixel-optimizer/shortpixel-image-optimiser#115]
Latest version (5.1.4) broken all my .svg images by trying to change `<img>` to `<picture>` e.g.

```
<img src="https://domain.tld/logo.svg" alt="aaa" width="216" height="36">
```

to

```
<picture class="sp-no-webp"><source srcset="https://domain.tld/logo.svg,https://domain.tld/logo.svg" type="image/webp"><source srcset="https://domain.tld/logo.svg" type="image/svg"><img src="https://domain.tld/logo.svg" class="sp-no-webp" alt="aaa" height="36" width="216" srcset="https://domain.tld/logo.svg"></picture>
```

In 5.1.3 working fine, by changing only `<img>` with jpg, png etc. to `<picture>` with avif and webp and ignoring svg.

**Comment by pdobrescu** [comment]
Thanks for reporting this @matt08, version 5.1.5 resolves this (to be released shortly).
