### ISSUE TITLE
Incorrect Seconds in a day

### ISSUE THREAD

**Issue by JusGu** [short-pixel-optimizer/shortpixel-image-optimiser#135]
QuotaController.php incorrectly assumes 84600 seconds are in a day. There are 86400 seconds in a day, not 84600 seconds, likely a typo.
https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/5050163a93fa10de46bc9d1dede446f5438462c1/class/Controller/QuotaController.php#L87-L88

**Comment by pdobrescu** [comment]
Thanks, @JusGu, this is a very good catch! And indeed, it's a typo, fixed in https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/commit/7a70353592945885844ea9bf456e1617d0741ff2, soon to be released.
