### ISSUE TITLE
Use absolute path for `require_once`

### ISSUE THREAD

**Issue by yaquawa** [short-pixel-optimizer/shortpixel-image-optimiser#17]
I got an error said it couldn't find the class `ShortPixel\Build\PackageLoader`.

The problem is this piece of code:

https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/d2923b8035de77b0700e36dfc3addd53422ba124/build/shortpixel/autoload.php#L2-L5

See [relative path in require_once doesn't work](https://stackoverflow.com/questions/5371828/relative-path-in-require-once-doesnt-work)

So instead, use this one:
```php
require_once __DIR__."/PackageLoader.php";
```

Also, you should always prefer absolute path to relative path when requiring file for much more better performance 😀

**Comment by bschuiling** [comment]
Hi, 

Thanks for letting us know you had an issue with this.  Do you know how I can reproduce this problem? On my installations it doesn't seem to be an issue. 

Anyhow, it will be fixed upcoming version, which should be out quite soon.

**Comment by yaquawa** [comment]
@bschuiling 
> Do you know how I can reproduce this problem? 
When I tried to activate the plugin this error occurred.

> Anyhow, it will be fixed upcoming version, which should be out quite soon.
Thanks!

**Comment by pdobrescu** [comment]
hi @yaquawa, can you please confirm that the notice is gone now? The fix @bschuiling was mentioning is already implemented for some time in the new plugin versions. Thanks!
