### ISSUE TITLE
Feature: Support for native lazyloading

### ISSUE THREAD

**Issue by goldfoot** [short-pixel-optimizer/shortpixel-image-optimiser#80]
Running plugin version 4.21.1 / Wordpress 5.6.1 on Apache and PHP 7.4.

This concerns the automatic delivery of webp-files in the frontend. My settings:

- Create WebP images
- Deliver the WebP versions of the images in the front-end: Using the <PICTURE> tag syntax
- Global (processes the whole output buffer before sending the HTML to the browser)

When the attribute `loading` is present on the `<img>` tag (e.g. `loading="lazy"`), it does not get copied to the output of the `<picture>` tag. Instead, it is omitted. It would be nice if it is added to the `<img>` tag inside `<picture>`.

**Comment by bschuiling** [comment]
You are correct. I've openened a task to bring back the lazy load tag in the child img tag if it's present in the original.

**Comment by pdobrescu** [comment]
This was fixed in https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/commit/97870472ca90128baa130ce33ac1bf6f217eba0c and released with version 4.22.0 but forgot to close the issue. 

Thanks for reporting it @goldfoot!
