### ISSUE TITLE
Issue with ShortPixel Adaptive Images Plugin Update

### ISSUE THREAD

**Issue by ArtMason** [short-pixel-optimizer/shortpixel-image-optimiser#85]
Good Day

I looked on the website but saw no support listed there.

This is in reference to ShortPixel Adaptive Images 2.3.0 after upgrading to 2.3.1 or 2.3.2

Upon update in the backend of Wordpress in the 'setting/shortpixel ai' it after upgrade states that the API key is invalid and the domain not registered. This is across all my wordpress site.

I downgraded the plugin to correct this. 

I wanted to make sure somone was aware. I am running WP 5.7.2 .

Thank you

Art

**Comment by pdobrescu** [comment]
Hello @ArtMason, apologies for the late reply here, I missed the notification of this issue. This repository is for our other plugin - ShortPixel Image Optimizer - therefore it isn't really relevant here, so I'm closing it. In case you still have issues, please add them to the [WordPress Support Forums](https://wordpress.org/support/plugin/shortpixel-adaptive-images/).
